# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 'https://RobBoothAppDev21.github.io/'
baseurl:             'til/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Rob Young
  url:               
  email:             robert.h.young@chicagobooth.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
